service: app-crypto-serverless

provider:
  name: aws
  region: eu-central-1
  runtime: provided.al2
  lambdaHashingVersion: 20201221

plugins:
  - ./vendor/bref/bref

functions:
  api:
    handler: 'public/index.php'
    description: ''
    timeout: 28
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      -   httpApi: '*'

package:
  patterns:
    - '!node_modules/**'
